version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "http://elasticbeanstalk-eu-west-1-337849790318.s3-website-eu-west-1.amazonaws.com"
        BUILD_ENV: "Default-Environment"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes